trigger:
- main

variables:
- group: vg-aks-liq

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: Tests
  displayName: 'TestAutomatizado'

  jobs:
  - job: RunTests
    displayName: 'TestsMaven'

    steps:

    - task: JavaToolInstaller@0
      displayName: 'InstalarJava'
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - script: |
        mvn clean test
      workingDirectory: 'Microservicio'
      displayName: 'TestAautomatizados'


- stage: AnalisisEstatico
  displayName: 'Analisis estatico de Codigo con Sonar'

  dependsOn: Tests
  condition: succeeded()

  jobs:
  - job: SonarCloud
    displayName: 'Analisis con Sonar Cloud'

    steps:

    - task: JavaToolInstaller@0
      displayName: 'Use Java 17'
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - script: |
        mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \ #comando que Sonar dice que se utilice
          -Dsonar.projectKey=gatoguerrero_Microservicio-Assessment
      workingDirectory: 'Microservicio'
      displayName: 'Análisis de Sonar Cloud'
      env:
        SONAR_TOKEN: $(SONAR_TOKEN) #Se la pasa como variable de entorno
